Repository ijlee2/ember-codemod-pod-to-octane, pull requests merged in 2024-10, with the labels that each got.

#65 Merged v1-addon and engine
  README.md
  bin/ember-codemod-pod-to-octane.ts
  src/index.ts
  src/migration/engine/index.ts
  src/migration/engine/steps/create-file-path-maps.ts
  src/migration/engine/steps/create-file-path-maps/addon/index.ts
  src/migration/engine/steps/create-file-path-maps/tests/index.ts
  src/migration/engine/steps/create-options.ts
  src/migration/engine/steps/index.ts
  src/migration/index.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/index.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-stylesheets.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/index.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/index.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-services.ts
  src/types/index.ts
  tests/fixtures/v1-addon/javascript/input/app/components/ui/form/field/styles.js
  tests/fixtures/v1-addon/javascript/input/app/components/ui/form/information/styles.js
  tests/fixtures/v1-addon/javascript/input/app/components/ui/form/styles.js
  tests/fixtures/v1-addon/sass/input/app/components/ui/form/field/styles.js
  tests/fixtures/v1-addon/sass/input/app/components/ui/form/information/styles.js
  tests/fixtures/v1-addon/sass/input/app/components/ui/form/styles.js
  tests/fixtures/v1-addon/typescript/input/app/components/ui/form/field/styles.js
  tests/fixtures/v1-addon/typescript/input/app/components/ui/form/information/styles.js
  tests/fixtures/v1-addon/typescript/input/app/components/ui/form/styles.js
  tests/helpers/shared-test-setups/engine/javascript.ts
  tests/helpers/shared-test-setups/engine/sass.ts
  tests/helpers/shared-test-setups/engine/typescript.ts
  tests/migration/engine/index/javascript.test.ts
  tests/migration/engine/index/sass.test.ts
  tests/migration/engine/index/typescript.test.ts
  tests/migration/engine/steps/create-file-path-maps/javascript.test.ts
  tests/migration/engine/steps/create-file-path-maps/sass.test.ts
  tests/migration/engine/steps/create-file-path-maps/typescript.test.ts
  tests/migration/engine/steps/create-options/javascript.test.ts
  tests/migration/engine/steps/create-options/sass.test.ts
  tests/migration/engine/steps/create-options/typescript.test.ts
  tests/migration/v1-addon/steps/create-file-path-maps/javascript.test.ts
  tests/migration/v1-addon/steps/create-file-path-maps/sass.test.ts
  tests/migration/v1-addon/steps/create-file-path-maps/typescript.test.ts
  update-test-fixtures.sh
Labels: enhance: code, breaking

#67 Removed unnecessary joins
  src/migration/app/steps/create-file-path-maps/app/map-component-classes.ts
  src/migration/app/steps/create-file-path-maps/app/map-component-stylesheets.ts
  src/migration/app/steps/create-file-path-maps/app/map-component-templates.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-adapters.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-controllers.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-models.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-routes.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-serializers.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-stylesheets.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/app/steps/create-file-path-maps/app/map-services.ts
  src/migration/app/steps/create-file-path-maps/tests/map-components.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/app/steps/create-file-path-maps/tests/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-services.ts
Labels: enhance: code

#69 move glob exclude patterns to ignoreList
  src/migration/app/steps/create-file-path-maps/app/map-route-stylesheets.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/app/steps/create-file-path-maps/tests/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-stylesheets.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-services.ts
Labels: enhance: code

#70 Documented how to use linters and incrementally migrate code
  README.md
  src/migration/app/steps/create-file-path-maps/app/map-component-classes.ts
  src/migration/app/steps/create-file-path-maps/app/map-component-stylesheets.ts
  src/migration/app/steps/create-file-path-maps/app/map-component-templates.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-adapters.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-controllers.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-models.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-routes.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-serializers.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-stylesheets.ts
  src/migration/app/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/app/steps/create-file-path-maps/app/map-services.ts
  src/migration/app/steps/create-file-path-maps/tests/map-components.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/app/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/app/steps/create-file-path-maps/tests/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-component-classes.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-component-stylesheets.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-component-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-stylesheets.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/addon/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-component-classes.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-component-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-route-templates.ts
  src/migration/v1-addon/steps/create-file-path-maps/app/map-services.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-components.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-controllers.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-route-routes.ts
  src/migration/v1-addon/steps/create-file-path-maps/tests/map-services.ts
  src/utils/files/rename-pod-path.ts
  tests/utils/files/rename-pod-path/base-case.test.ts
  tests/utils/files/rename-pod-path/edge-case-replace-suffixes-file-name.test.ts
  tests/utils/files/rename-pod-path/error-handling-directory-does-not-match.test.ts
Labels: enhance: documentation, enhance: code
